name: "🏇 Benchmarks"

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  run-benchmarks:
    name: 🏄 Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: 🔟 Save Pull Request Number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: echo $PR_NUMBER > pr_number.meta

      - name: 🔧 Use .NET Core 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 🔬 Test
        run: "dotnet run
          --project ./test/Tethos.Benchmarks/\
          Tethos.Benchmarks.csproj
          --configuration Release"

      - name: 📚 Publish results
        uses: actions/upload-artifact@v5
        with:
          name: benchmark-results
          path: |
            **/*.meta
            BenchmarkDotNet.Artifacts/results/**
