name: "🏅 Test Report"

on:
  workflow_run:
    workflows: ["🔄 CI", "🏄 Performance"]
    types: ["completed"]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: dawidd6/action-download-artifact@v17
        with:
          workflow: performance.yml
          name: performance-test-results

      - uses: dawidd6/action-download-artifact@v17
        with:
          workflow: ci.yml
          name: test-results

      - uses: dorny/test-reporter@v2
        with:
          name: 📜 Test Report
          path: "**/*.trx"
          reporter: dotnet-trx
