name: "🏅 Test Report"

on:
  workflow_run:
    workflows: ["🔄 CI", "🏄 Performance"]
    types: ["completed"]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: performance.yml
          name: performance-test-results

      - uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          name: test-results

      - uses: dorny/test-reporter@v1
        with:
          name: 📜 Test Report
          path: "**/*.trx"
          reporter: dotnet-trx
